In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
data = {
    "Year": [2019, 2020, 2021, 2022, 2023],

    "Mean_Probability": [
        0.028098194,
        0.038819492,
        0.029070187,
        0.027550494,
        0.03103549
    ],

    "Very_Low": [
        10584230,
        10401174,
        10545356,
        10598471,
        10557150
    ],

    "Low": [
        41443,
        147894,
        97320,
        34308,
        40104
    ],

    "Moderate": [
        30181,
        49295,
        39733,
        26400,
        33830
    ],

    "High": [
        36791,
        31108,
        45215,
        45519,
        37912
    ],

    "Very_High": [
        158891,
        222065,
        123912,
        146838,
        182540
    ]
}

temporal_df = pd.DataFrame(data)

temporal_df

   Year  Mean_Probability  Very_Low     Low  Moderate   High  Very_High
0  2019          0.028098  10584230   41443     30181  36791     158891
1  2020          0.038819  10401174  147894     49295  31108     222065
2  2021          0.029070  10545356   97320     39733  45215     123912
3  2022          0.027550  10598471   34308     26400  45519     146838
4  2023          0.031035  10557150   40104     33830  37912     182540

In [3]:
class_columns = [
    "Very_Low",
    "Low",
    "Moderate",
    "High",
    "Very_High"
]

total_pixels = temporal_df[class_columns].sum(axis=1)

for col in class_columns:
    temporal_df[col + "_Percent"] = (
        temporal_df[col] / total_pixels * 100
    )

temporal_df

,Year,Mean_Probability,Very_Low,Low,Moderate,High,Very_High,Very_Low_Percent,Low_Percent,Moderate_Percent,High_Percent,Very_High_Percent
0,2019,0.028098,10584230,41443,30181,36791,158891,97.536699,0.381909,0.278127,0.339040,1.464226
1,2020,0.038819,10401174,147894,49295,31108,222065,95.849786,1.362885,0.454267,0.286669,2.046392
2,2021,0.029070,10545356,97320,39733,45215,123912,97.178464,0.896832,0.366151,0.416669,1.141884
3,2022,0.027550,10598471,34308,26400,45519,146838,97.667934,0.316158,0.243284,0.419471,1.353154
4,2023,0.031035,10557150,40104,33830,37912,182540,97.287149,0.369570,0.311753,0.349370,1.682158

In [6]:
import os

# Create the results folder
PROJECT_DIR = os.path.abspath(
    os.path.join(os.getcwd(), "..")
)

RESULTS_DIR = os.path.join(PROJECT_DIR, "results")
os.makedirs(RESULTS_DIR, exist_ok=True)

# Save the summary table
summary_path = os.path.join(
    RESULTS_DIR,
    "temporal_susceptibility_summary_2019_2023.csv"
)

summary_df.to_csv(summary_path, index=False)

print("CSV saved successfully!")

print("File location:", summary_path)

NameError: name 'summary_df' is not defined